# Generated by Django 3.2.9 on 2021-12-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dennislvy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
